---
#tomcat
#  - name: add tomcat group
#    group:
#        name: tomcat
#  - name: add tomcat user
#    user:
#        name: tomcat
#        group: tomcat
#        home: /user/share/tomcat
#        createhome: no
  - name: create /opt/tomcat directory
    file:
      path: /opt/tomcat
      state: directory
      mode: 0755
  - name: Installing Latest version of Apache
    yum:
      pkg: httpd
      state: latest
  - name: Copying the demo file
    copy:
      src: /etc/ansible/index.html
      dest: /var/www/html
#  - name: Enable it on System Boot
#    service:
#      name: httpd
#      enabled: yes
#    notify:
#      - start apache
#    handlers:
  - name: start apache
    service: name=httpd state=started
  - name: download & unarchive
    unarchive:
      src: "{{download_url}}"
      dest: /opt/tomcat
      remote_src: yes
      extra_opts: [--strip-components=1]
  - name: Change ownership
    file:
      path: /opt/tomcat
      owner: ansible
      group: ansible
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
      state: directory
  - name: Copy Tomcat service from local to remote
    copy:
      src: /etc/ansible/roles/tomcat/tomcat.service
      dest: /etc/systemd/system/
      mode: 0755
  - name: edit tomcat-users.xml
    blockinfile:
      dest: /opt/tomcat/conf/tomcat-users.xml
      insertafter: <tomcat-users>
      block: |
          <role rolename = "admin-gui" />
          <role rolename = "manager-gui" />
          <user username = "ansible" password = "123456789" roles = "admin-gui, manager-gui" />
  - name: Start and enable Tomcat service
    systemd:
      name: tomcat
      state: started
      enabled: true
      daemon_reload: true
