---
  - name: Create an EC2 key

    ec2_key:
      aws_access_key: AKIASM343RWKRW7JVZ7C
      aws_secret_key: 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
      name: "aws_private.pem"
      region: "{{ region }}"
    register: ec2_key

  - name: Save private key
    copy: content="{{ ec2_key.key.private_key }}" dest=/home/ansible/aws_private.pem mode=0600
    when: ec2_key.changed

  - name: Create an ec2 instance
    ec2:
      aws_access_key: AKIASM343RWKRW7JVZ7C
      aws_secret_key: 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
      key_name: aws_private
      group: "{{ security_group_id }}"
      instance_type: "{{ instance_type}}"
      image: "{{ ami }}"
      wait: true
      region: "{{ region }}"
      count: 1 # default
      count_tag:
        Name: Demo
      instance_tags:
        Name: Demo
      vpc_subnet_id: "{{ subnetid }}"
      assign_public_ip: yes
    register: ec2